const pool = require('../config/database');

// Curated bank of short-form (YouTube Shorts / Instagram Reels / TikTok)
// video script ideas, each promoting one specific free tool. Source of
// truth lives here in code (not hand-edited in the DB) — mirrors the
// toolLeadEmailSequence.js pattern: syncVideoScriptIdeas() upserts this
// array into the DB on every boot, so adding/editing a script is just a
// code change + deploy, and the `key` column keeps the upsert idempotent.
//
// CTA is platform-aware on purpose: YouTube comments render links as
// clickable, so "link in the first comment" works there and should point
// straight at the specific tool page (pin that comment after posting).
// Instagram/TikTok never make links in captions or comments clickable,
// so "link in bio" is the only functional CTA — the bio link should point
// at https://travelsmarterapp.com/free-travel-tools.html (the hub), not
// any single tool, since the same bio link has to work across videos
// promoting different tools.
const SCRIPT_IDEAS = [
  {
    key: 'resort-fee-vegas-lie',
    toolSlug: 'resort-fee-checker',
    toolName: 'Resort Fee Checker',
    hook: "Your $99 Vegas hotel room is a lie",
    voiceover: "You booked a $99 room in Vegas. At checkout, it's $140. That extra $41 a night? A 'resort fee' — for a pool you didn't use and wifi you already have on your phone. It's not optional, and it's almost never in the price you see when booking. Before you book anywhere in Vegas, Orlando, or Miami — check if there's a hidden resort fee first.",
    ctaYoutube: "Free Resort Fee Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Resort Fee Checker — link in bio",
    caption: "The hotel price you see is almost never the price you pay 💸",
    hashtags: "#travelhacks #vegastravel #hiddenfees #traveltiktok",
  },
  {
    key: 'medication-legality-japan',
    toolSlug: 'medication-legality-checker',
    toolName: 'Medication Legality Checker',
    hook: "Your prescription could get you arrested in Japan",
    voiceover: "Adderall — totally normal in the US — is a controlled substance in Japan and South Korea. Bring it without checking, and it can be confiscated at customs, or worse. Same goes for some common painkillers in Greece and Egypt. Always check your destination's medication rules before you pack your prescriptions — not after you land.",
    ctaYoutube: "Free Medication Legality Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Medication Legality Checker — link in bio",
    caption: "Don't find out at customs 💊✈️",
    hashtags: "#traveltips #packingtips #traveladvice",
  },
  {
    key: 'customs-800-loophole',
    toolSlug: 'customs-checker',
    toolName: 'Customs Checker',
    hook: "You have $800 you didn't know about",
    voiceover: "Every time you fly back to the US, you get an $800 duty-free exemption — no tax on souvenirs, gifts, anything you bought, up to that amount. Most travelers have no idea it exists, or how close they are to the limit. Check your destination's exact duty-free allowance before your next shopping spree abroad.",
    ctaYoutube: "Free Customs Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Customs Checker — link in bio",
    caption: "The $800 loophole nobody tells you about 💰",
    hashtags: "#travelmoney #dutyfree #traveltips",
  },
  {
    key: 'tipping-japan-rude',
    toolSlug: 'tipping-calculator',
    toolName: 'Tipping Calculator',
    hook: "Tipping in Japan is actually rude",
    voiceover: "In the US, not tipping 20% gets you side-eye. In Japan, tipping at all can be seen as insulting — like you think they need the extra cash to do their job well. Meanwhile in France, an 18% service charge is already built into your bill by law. Tipping culture flips completely by country — check before your next trip so you don't offend anyone, or underpay.",
    ctaYoutube: "Free Tipping Calculator — link in the first comment 👇",
    ctaReelsTiktok: "Free Tipping Calculator — link in bio",
    caption: "One habit, two totally opposite reactions 🌍",
    hashtags: "#tippingculture #traveletiquette #japantravel",
  },
  {
    key: 'vape-illegal-southeast-asia',
    toolSlug: 'smoking-vaping-checker',
    toolName: 'Smoking & Vaping Legality Checker',
    hook: "Your vape is illegal the second you land",
    voiceover: "Vapes are completely normal at home. In Thailand, Singapore, and Vietnam? Straight-up illegal — confiscated at customs, sometimes with a fine attached. 'I didn't know' doesn't help once it's already in a bin. Always check local vaping and smoking laws before you pack — it takes ten seconds.",
    ctaYoutube: "Free Smoking & Vaping Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Smoking & Vaping Checker — link in bio",
    caption: "Packed like normal, landed in trouble 🚭",
    hashtags: "#travelmistakes #southeastasiatravel #traveltips",
  },
  {
    key: 'passport-rule-strands-travelers',
    toolSlug: 'visa-requirement-checker',
    toolName: 'Visa Requirement Checker',
    hook: "The passport rule that strands more travelers than visas",
    voiceover: "Everyone worries about visas. The rule that actually strands travelers is passport validity — many countries require six months of validity beyond your travel dates, not just past your return date. Airlines check this at the gate, before you even reach immigration. Miss it, and you don't fly at all.",
    ctaYoutube: "Free Visa & Passport Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Visa & Passport Checker — link in bio",
    caption: "The rule nobody checks until it's too late ✈️😬",
    hashtags: "#traveltips #passporttips #travelmistakes",
  },
  {
    key: 'passport-valid-not-valid-enough',
    toolSlug: 'passport-validity-checker',
    toolName: 'Passport Validity Checker',
    hook: "Your passport can be 'valid' and still get you denied boarding",
    voiceover: "Your passport says it's valid until next March. Doesn't matter — if your destination requires six months of validity beyond your travel dates and you're inside that window, airlines will deny boarding on the spot. This trips up more travelers than any visa rule. Check your exact dates before you book, not before you fly.",
    ctaYoutube: "Free Passport Validity Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Passport Validity Checker — link in bio",
    caption: "Valid ≠ valid enough 🛂",
    hashtags: "#passporttips #traveltips #travelhacks",
  },
  {
    key: 'vat-refund-uk-killed-it',
    toolSlug: 'vat-refund-checker',
    toolName: 'VAT Refund Checker',
    hook: "The UK quietly killed tax-free shopping and nobody told you",
    voiceover: "Up until 2021, tourists could get a VAT refund shopping in the UK. Not anymore — it's gone, and a lot of travelers still don't know. Meanwhile the US and Canada never had a national refund scheme at all, while most of the EU, Japan, and South Korea still refund 10 to 25 percent. Check before you budget your shopping.",
    ctaYoutube: "Free VAT Refund Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free VAT Refund Checker — link in bio",
    caption: "Still budgeting for a refund that doesn't exist anymore? 🧾",
    hashtags: "#traveltips #shoppingtips #europetravel",
  },
  {
    key: 'atm-popup-always-say-no',
    toolSlug: 'atm-fee-checker',
    toolName: 'ATM Fee Checker',
    hook: "Always say no to this ATM popup",
    voiceover: "When a foreign ATM asks if you want to be charged in your home currency, that's Dynamic Currency Conversion — and it always means a worse exchange rate with a hidden markup. Always choose to be charged in the local currency instead. It's one tap, and it saves you real money every single withdrawal.",
    ctaYoutube: "Free ATM Fee Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free ATM Fee Checker — link in bio",
    caption: "One wrong tap costs you every time you withdraw 💸",
    hashtags: "#travelmoney #traveltips #moneysavingtips",
  },
  {
    key: 'tourist-tax-cash-only-surprise',
    toolSlug: 'tourist-tax-checker',
    toolName: 'Tourist Tax Checker',
    hook: "The hotel fee that's cash-only and never in your booking price",
    voiceover: "Booking sites almost never show you the nightly tourist tax a lot of cities charge — and it's often cash-only, paid directly at check-in. Show up without local cash and it's an awkward moment at the front desk. Budget a small buffer and check the local tourist tax before you go.",
    ctaYoutube: "Free Tourist Tax Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Tourist Tax Checker — link in bio",
    caption: "The fee your booking confirmation never mentions 🏨",
    hashtags: "#traveltips #europetravel #hiddenfees",
  },
  {
    key: 'departure-tax-miss-flight',
    toolSlug: 'departure-tax-checker',
    toolName: 'Departure Tax Checker',
    hook: "The cash-only fee that catches travelers at the gate",
    voiceover: "Most departure taxes are baked into your ticket price now — but a handful of countries still require a separate cash payment right at the airport before you fly out. Show up without local currency and you could genuinely miss your flight over it. A 30-second check saves you the scramble.",
    ctaYoutube: "Free Departure Tax Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Departure Tax Checker — link in bio",
    caption: "The fee that can make you miss your flight 🛫",
    hashtags: "#traveltips #travelhacks #airporttips",
  },
  {
    key: 'water-safety-ice-cubes',
    toolSlug: 'water-safety-checker',
    toolName: 'Tap Water Safety Checker',
    hook: "You know not to drink the tap water. You forgot about the ice",
    voiceover: "Most travelers already know not to drink tap water somewhere risky. What they forget is that ice cubes and salads washed in tap water carry the exact same risk — and they're way easier to overlook. Check the water safety rating for your destination before you order that iced coffee.",
    ctaYoutube: "Free Tap Water Safety Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Tap Water Safety Checker — link in bio",
    caption: "It's not the water you're avoiding, it's the ice 🧊",
    hashtags: "#traveltips #travelhealth #foodsafety",
  },
  {
    key: 'wildlife-venom-movie-advice',
    toolSlug: 'wildlife-safety-checker',
    toolName: 'Wildlife Safety Checker',
    hook: "If you get bitten by something venomous, forget everything you've seen in movies",
    voiceover: "Sucking out venom, using a tourniquet — that outdated advice can actually make a venomous bite or sting worse. The real move: stay calm, keep the limb still, and get to medical care immediately. Know the wildlife risk at your destination before you go, not after something happens.",
    ctaYoutube: "Free Wildlife Safety Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Wildlife Safety Checker — link in bio",
    caption: "The movie advice that makes a venomous bite worse 🐍",
    hashtags: "#travelsafety #traveltips #outdoortravel",
  },
  {
    key: 'hurricane-season-beach-trip',
    toolSlug: 'natural-disaster-checker',
    toolName: 'Natural Disaster Risk Checker',
    hook: "You just booked a beach trip during hurricane season",
    voiceover: "Mexico's Caribbean coast, Vietnam, the Philippines — all gorgeous, all with a defined hurricane or typhoon season that a lot of travelers book straight through without checking. Know the riskiest months before you commit, and make sure your travel insurance actually covers named-storm evacuation.",
    ctaYoutube: "Free Natural Disaster Risk Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Natural Disaster Risk Checker — link in bio",
    caption: "Check the season before you check the flight price 🌀",
    hashtags: "#traveltips #hurricaneseason #beachvacation",
  },
  {
    key: 'emergency-911-doesnt-work',
    toolSlug: 'emergency-number-checker',
    toolName: 'Emergency Number Checker',
    hook: "911 doesn't work almost anywhere outside the US",
    voiceover: "Dial 911 in most of the world and nothing happens. Every country has its own emergency number — some split police, fire, and ambulance into three completely different numbers. Save your destination's actual emergency number before you land, not while you're trying to remember it during an emergency.",
    ctaYoutube: "Free Emergency Number Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Emergency Number Checker — link in bio",
    caption: "The number that only works in one country 🚨",
    hashtags: "#traveltips #travelsafety #traveladvice",
  },
  {
    key: 'uber-exited-markets',
    toolSlug: 'rideshare-checker',
    toolName: 'Rideshare Availability Checker',
    hook: "Uber isn't everywhere you'd expect",
    voiceover: "Uber has fully exited entire markets — Southeast Asia, mainland China, Denmark — in favor of local apps you've probably never heard of. Show up assuming Uber will be there and you can end up stranded outside the airport at midnight. Check what actually works at your destination before you land.",
    ctaYoutube: "Free Rideshare Availability Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Rideshare Availability Checker — link in bio",
    caption: "Don't find out Uber left the country at midnight 🚕",
    hashtags: "#traveltips #travelhacks #travelfail",
  },
  {
    key: 'drone-confiscated-no-permit',
    toolSlug: 'drone-checker',
    toolName: 'Drone Rules Checker',
    hook: "Your drone can get confiscated before you even take off",
    voiceover: "A lot of countries require drone registration before you fly, and some ban them completely in historic centers, near government buildings, or entire cities. Fly without checking, and the drone doesn't come home with you. Always check local drone rules before you pack it — registration usually can't be done last-minute anyway.",
    ctaYoutube: "Free Drone Rules Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Drone Rules Checker — link in bio",
    caption: "Packed the drone, forgot to check the law 🛸",
    hashtags: "#dronetravel #traveltips #travelvlog",
  },
  {
    key: 'vpn-blocked-once-landed',
    toolSlug: 'vpn-censorship-checker',
    toolName: 'VPN & Censorship Checker',
    hook: "Set up your VPN before you land in China, not after",
    voiceover: "In heavily censored countries, the VPN provider's own website and app store listing are often blocked too — so if you land without one already installed and tested, you may not be able to get one at all. Set it up, test it, and make sure it actually works before you fly, not once you're already offline.",
    ctaYoutube: "Free VPN & Censorship Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free VPN & Censorship Checker — link in bio",
    caption: "You can't download a VPN once you can't access the internet 🌐",
    hashtags: "#traveltips #digitalnomad #chinatravel",
  },
  {
    key: 'temple-dress-code-turned-away',
    toolSlug: 'dress-code-checker',
    toolName: 'Dress Code Checker',
    hook: "The temple visit that turns you away at the door",
    voiceover: "Shoulders and knees covered — a lot of temples, mosques, and churches enforce that strictly, no exceptions, no rentals available on-site half the time. Pack one lightweight scarf or sarong and an unplanned temple stop never turns into a wasted trip. Check the local dress code before you go.",
    ctaYoutube: "Free Dress Code Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Dress Code Checker — link in bio",
    caption: "Turned away at the door over a pair of shorts 👗",
    hashtags: "#traveltips #templetravel #packingtips",
  },
  {
    key: 'drinking-age-16-vs-21',
    toolSlug: 'drinking-age-checker',
    toolName: 'Legal Drinking Age Checker',
    hook: "Legal at 16 here. Illegal at 21 two borders over",
    voiceover: "The legal drinking age swings from 16 in parts of Europe to 21 in the US, with genuine surprises in between — Japan keeps it at 20 even though adulthood there starts at 18. If you're anywhere near the threshold, ID checks are routine. Check the actual local age before you order.",
    ctaYoutube: "Free Legal Drinking Age Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Legal Drinking Age Checker — link in bio",
    caption: "Same age, completely different rules by country 🍻",
    hashtags: "#traveltips #travelfacts #partytravel",
  },
  {
    key: 'rental-age-hidden-surcharge',
    toolSlug: 'rental-age-checker',
    toolName: 'Car Rental Age Checker',
    hook: "The rental car fee that never shows up in the online quote",
    voiceover: "Book a rental under 25 and the online price looks totally normal — until you're at the counter and a young-driver surcharge suddenly appears, sometimes doubling the total. It's almost never disclosed upfront. Check your destination's age rules before you book, not after you're already standing at the desk.",
    ctaYoutube: "Free Car Rental Age Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Car Rental Age Checker — link in bio",
    caption: "The fee that only appears once you're at the counter 🚗",
    hashtags: "#traveltips #rentalcar #budgettravel",
  },
  {
    key: 'germany-sunday-everything-closed',
    toolSlug: 'business-hours-checker',
    toolName: 'Business Hours Checker',
    hook: "Showing up in Germany on a Sunday? Everything's closed",
    voiceover: "Germany, Austria, and Switzerland close almost everything on Sundays — by law, not just habit. Meanwhile Israel and Jordan shift their entire weekend to Friday and Saturday. Plan a shopping day or errands around the wrong day, and you'll be standing outside locked doors. Check the local weekend before you plan around it.",
    ctaYoutube: "Free Business Hours Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Business Hours Checker — link in bio",
    caption: "Wrong day, wrong country, everything's closed 🕒",
    hashtags: "#traveltips #europetravel #travelmistakes",
  },
  {
    key: 'modern-countries-cash-only',
    toolSlug: 'currency-checker',
    toolName: 'Currency & Cash Culture Checker',
    hook: "Some of the 'most modern' countries are surprisingly cash-only",
    voiceover: "You'd assume a developed, modern country means card everywhere — but some of the most advanced economies are still surprisingly cash-heavy in daily life, small vendors especially. Don't assume card-only just because a country feels modern. Check the actual cash culture before you land with an empty wallet.",
    ctaYoutube: "Free Currency & Cash Culture Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Currency & Cash Culture Checker — link in bio",
    caption: "Modern doesn't always mean cashless 💳",
    hashtags: "#traveltips #travelmoney #traveladvice",
  },
  {
    key: 'airport-sim-kiosk-worst-deal',
    toolSlug: 'sim-checker',
    toolName: 'SIM & eSIM Checker',
    hook: "The airport SIM kiosk is the worst deal in the airport",
    voiceover: "That SIM card kiosk right after baggage claim is convenient, and it is almost never the cheapest option. An eSIM bought in advance usually beats it on both price and setup time — and you land already connected instead of standing in line. Check your destination's best SIM option before you fly.",
    ctaYoutube: "Free SIM & eSIM Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free SIM & eSIM Checker — link in bio",
    caption: "Land already connected instead of standing in that line 📱",
    hashtags: "#traveltips #esim #travelhacks",
  },
  {
    key: 'pet-travel-months-not-weeks',
    toolSlug: 'pet-travel-checker',
    toolName: 'Pet Travel Checker',
    hook: "Bringing your dog to a rabies-free country takes months of prep, not weeks",
    voiceover: "Australia, Iceland, a handful of Caribbean islands — rabies-free destinations often require blood tests with mandatory waiting periods before your pet can even qualify to travel. This is the one piece of trip prep that genuinely cannot be rushed. Check your destination's pet import rules the moment you start planning.",
    ctaYoutube: "Free Pet Travel Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Pet Travel Checker — link in bio",
    caption: "The trip prep that can't be rushed, no matter how much you pay 🐾",
    hashtags: "#travelwithpets #petsoftiktok #traveltips",
  },
  {
    key: 'travel-advisory-level-hides-nuance',
    toolSlug: 'travel-advisory-checker',
    toolName: 'Travel Advisory Checker',
    hook: "\"Is it safe?\" has a more complicated answer than you think",
    voiceover: "A country's travel advisory level is a national average — it can hide a lot. Somewhere can be genuinely safe in its main tourist areas and a real risk somewhere else in the same country. The level tells you where to start, not the whole story. Always check the specific reason behind the rating, and confirm against your own government's official advisory before you book.",
    ctaYoutube: "Free Travel Advisory Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Travel Advisory Checker — link in bio",
    caption: "The safety rating that's more nuanced than a single number 🛡️",
    hashtags: "#traveltips #travelsafety #traveladvice",
  },
  {
    key: 'lgbtq-legal-status-swings-wildly',
    toolSlug: 'lgbtq-travel-safety-checker',
    toolName: 'LGBTQ+ Travel Safety Checker',
    hook: "Legal in one country, criminalized a few hours' flight away",
    voiceover: "Same-sex relationships are legally recognized with full protections in some countries — and criminalized under the law in others, sometimes just a short flight apart. Laws in this specific area have been changing fast, in both directions, in a lot of places recently. Always check the current, city-level detail for your exact destination before you book, not just the country in general.",
    ctaYoutube: "Free LGBTQ+ Travel Safety Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free LGBTQ+ Travel Safety Checker — link in bio",
    caption: "The travel-planning check that genuinely matters 🏳️‍🌈",
    hashtags: "#traveltips #lgbtqtravel #travelsafety",
  },
  {
    key: 'priority-pass-doesnt-work-your-hub',
    toolSlug: 'lounge-access-checker',
    toolName: 'Airport Lounge Access Checker',
    hook: "Your Priority Pass might be useless at your own home airport",
    voiceover: "At airports run by one dominant airline — Delta Sky Clubs at Atlanta, United Clubs at Chicago O'Hare — Priority Pass often only gets you a restaurant credit, not an actual lounge. You paid for the membership and still can't get in. Always check your specific airport's Priority Pass coverage before you count on it.",
    ctaYoutube: "Free Airport Lounge Access Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Airport Lounge Access Checker — link in bio",
    caption: "The card perk that quietly doesn't work everywhere 🛋️",
    hashtags: "#travelhacks #prioritypass #traveltips",
  },
  {
    key: 'accessible-travel-historic-charm-vs-access',
    toolSlug: 'accessible-travel-checker',
    toolName: 'Accessible & Wheelchair Travel Checker',
    hook: "The most charming parts of a city are often the least accessible",
    voiceover: "Modern hotels and museums are genuinely accessible almost everywhere now. It's the historic old towns — centuries-old cobblestones, ancient stairs, narrow doorways — where real, often unavoidable barriers show up, no matter how much a country has invested elsewhere. Before you book, check accessibility for the specific neighborhood you're staying in, not just the country in general.",
    ctaYoutube: "Free Accessible Travel Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Accessible Travel Checker — link in bio",
    caption: "Charming for some, a real barrier for others ♿",
    hashtags: "#accessibletravel #traveltips #wheelchairtravel",
  },
  {
    key: 'holiday-season-golden-week-wrecks-trips',
    toolSlug: 'holiday-season-checker',
    toolName: 'National Holiday Season Checker',
    hook: "You didn't check the calendar. Now every train in the country is sold out",
    voiceover: "China's Spring Festival, Japan's Golden Week, Brazil's Carnival, Vietnam's Tet — these aren't single-day closures like a public holiday. They're weeks where trains and hotels book out nationwide and prices spike hard. Checking the weather forecast isn't enough — check your destination's disruptive holiday season before you lock in your dates.",
    ctaYoutube: "Free National Holiday Season Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free National Holiday Season Checker — link in bio",
    caption: "The calendar check that saves your whole trip 📅",
    hashtags: "#traveltips #travelplanning #travelhacks",
  },
  {
    key: 'overweight-baggage-3lb-costs-more-than-ticket',
    toolSlug: 'overweight-baggage-checker',
    toolName: 'Overweight & Oversized Baggage Fee Checker',
    hook: "3 extra pounds just cost more than your actual plane ticket",
    voiceover: "Budget airlines like Ryanair and Wizz Air don't just charge a flat overweight fee — they charge per kilo, and at the gate that can hit €10-12 per kilo. A bag that's just a few pounds over the limit can cost you more than the flight itself. Pre-booking extra weight online instead of at the gate is dramatically cheaper — and a $15 luggage scale at home pays for itself the first time it saves you this fee.",
    ctaYoutube: "Free Overweight Baggage Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Overweight Baggage Checker — link in bio",
    caption: "The fee that can cost more than the flight 🧳",
    hashtags: "#travelhacks #budgettravel #traveltips",
  },
  {
    key: 'photography-tripod-permit-surprise',
    toolSlug: 'photography-permit-checker',
    toolName: 'Photography & Filming Permit Checker',
    hook: "Your tripod might need a permit you don't even know about",
    voiceover: "Casual photos are fine almost everywhere. But set up a tripod at the Louvre, the Uffizi, or Machu Picchu, and you can suddenly need a separate permit or fee you never planned for. It's not about the country's laws in general — it's the specific site. Check before you pack the tripod, not when a guard stops you.",
    ctaYoutube: "Free Photography & Filming Permit Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Photography & Filming Permit Checker — link in bio",
    caption: "The gear rule nobody checks until it's too late 📷",
    hashtags: "#traveltips #travelphotography #travelhacks",
  },
  {
    key: 'souvenir-buddha-statue-not-legal',
    toolSlug: 'souvenir-export-checker',
    toolName: 'Souvenir & Prohibited Export Items Checker',
    hook: "That souvenir you just bought might not be legal to take home",
    voiceover: "A Buddha statue in Thailand. Ancient coins in Greece. Ivory almost anywhere. Some of the most tempting souvenirs are either banned outright or need an official export permit you didn't know existed — and customs finds out at the worst possible moment, right as you're trying to leave. Check before you buy, not after it's already confiscated.",
    ctaYoutube: "Free Souvenir & Export Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Souvenir & Export Checker — link in bio",
    caption: "The souvenir that gets confiscated at the airport 🛍️",
    hashtags: "#traveltips #travelhacks #travelmistakes",
  },
  {
    key: 'tourist-scams-know-before-you-land',
    toolSlug: 'tourist-scams-checker',
    toolName: 'Common Tourist Scams Checker',
    hook: "The #1 tourist scam in your destination — before you land",
    voiceover: "A friendly stranger in Budapest who invites you to 'their favorite bar.' A Bangkok tuk-tuk driver who says the temple is 'closed today.' A fake student in Beijing inviting you to a tea ceremony. Every destination has one scam that catches more tourists than any other, and it almost always starts with someone being unusually friendly. Know what it looks like before you go, and it can't work on you.",
    ctaYoutube: "Free Tourist Scams Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Tourist Scams Checker — link in bio",
    caption: "The scam that gets tourists every single time 🎭",
    hashtags: "#traveltips #travelhacks #travelsafety",
  },
  {
    key: 'lost-baggage-compensation-owed',
    toolSlug: 'lost-baggage-checker',
    toolName: 'Lost or Damaged Baggage Compensation Checker',
    hook: "If the airline loses your bag, you're owed way more than you think",
    voiceover: "Most people just accept it when an airline loses or damages their checked bag. But you're actually entitled to real compensation — up to $3,800 on a US domestic flight, or around 1,700 dollars internationally under the Montreal Convention. The catch: there are strict deadlines to file, as short as 7 days for damage. Know the number and the deadline before it happens, not after.",
    ctaYoutube: "Free Lost Baggage Compensation Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Lost Baggage Compensation Checker — link in bio",
    caption: "What airlines don't tell you when they lose your bag 🧳",
    hashtags: "#traveltips #travelhacks #flightcompensation",
  },
  {
    key: 'cash-declaration-limit-before-customs',
    toolSlug: 'cash-declaration-checker',
    toolName: 'Cash Declaration Limit Checker',
    hook: "Carrying cash on your trip? Know this number first",
    voiceover: "Almost every country has a cash declaration limit — often around $10,000, but in some places it's way lower, like $5,000 in Turkey or Vietnam. Go over it without declaring, and customs can legally seize the entire amount on the spot, even if it's completely legitimate money. Know the number for your destination before you pack your wallet, not after you're standing in a customs line.",
    ctaYoutube: "Free Cash Declaration Limit Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Cash Declaration Limit Checker — link in bio",
    caption: "The number that decides if customs keeps your cash 💵",
    hashtags: "#traveltips #travelhacks #travelmoney",
  },
  {
    key: 'yellow-fever-certificate-entry-requirement',
    toolSlug: 'yellow-fever-checker',
    toolName: 'Yellow Fever Certificate Requirement Checker',
    hook: "This isn't optional — some countries won't let you in without it",
    voiceover: "There's a difference between 'you should get this vaccine' and 'you legally cannot enter without proof of this vaccine.' Some countries require a yellow fever certificate for literally every traveler, others only if you're arriving from a specific at-risk country — and if you show up without it where required, you can be denied boarding at check-in or quarantined the moment you land. Check the actual requirement for your destination, not just the general advice.",
    ctaYoutube: "Free Yellow Fever Certificate Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Yellow Fever Certificate Checker — link in bio",
    caption: "The vaccine that's actually a legal requirement, not just advice 💉",
    hashtags: "#traveltips #travelhacks #traveldocuments",
  },
  {
    key: 'digital-nomad-visa-real-program',
    toolSlug: 'digital-nomad-visa-checker',
    toolName: 'Digital Nomad Visa Checker',
    hook: "Working remotely on this trip? There might be an actual visa for that",
    voiceover: "A tourist visa technically doesn't let you work, even remotely for a company back home — but a growing list of countries now have a real, dedicated digital nomad visa instead. Portugal, Spain, Costa Rica, Thailand's new DTV, Colombia, Brazil — each has its own income requirement and duration, and they're nothing like a standard tourist visa. If you're planning to work while you travel, this is the thing to check first, not after you land.",
    ctaYoutube: "Free Digital Nomad Visa Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Digital Nomad Visa Checker — link in bio",
    caption: "The visa most remote workers don't know exists 💻",
    hashtags: "#digitalnomad #traveltips #remotework",
  },
  {
    key: 'solo-female-travel-honest-orientation',
    toolSlug: 'solo-female-travel-checker',
    toolName: 'Solo Female Travel Safety Checker',
    hook: "Is it actually safe for a woman to travel here alone?",
    voiceover: "General crime advisories don't tell you what solo female travelers actually want to know — is the staring going to be intense, is catcalling common, do I need to dress more conservatively than I planned? Some destinations are consistently rated as some of the most comfortable in the world for women alone, others genuinely require extra caution, and most fall somewhere in between with millions of women still visiting safely every year. Get the honest, specific picture for your destination before you go.",
    ctaYoutube: "Free Solo Female Travel Safety Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Solo Female Travel Safety Checker — link in bio",
    caption: "The question every solo female traveler asks before booking 🧭",
    hashtags: "#solofemaletravel #traveltips #travelsafety",
  },
  {
    key: 'minor-consent-letter-single-parent',
    toolSlug: 'minor-consent-checker',
    toolName: 'Minor Travel Consent Letter Checker',
    hook: "Traveling with your kid but not your co-parent? Do this first",
    voiceover: "South Africa is the famous horror story — families turned away at the airport because they didn't have the right paperwork for their own child. But it's not just South Africa. Mexico, Canada, and several Latin American countries actively check for a notarized letter proving the other parent consented to the trip. It costs almost nothing and takes ten minutes to get notarized — and it's the difference between boarding your flight and standing in an airport office arguing with an immigration officer.",
    ctaYoutube: "Free Minor Travel Consent Checker — link in the first comment 👇",
    ctaReelsTiktok: "Free Minor Travel Consent Checker — link in bio",
    caption: "The document that saves your family trip 👨‍👩‍👧",
    hashtags: "#familytravel #traveltips #travelhacks",
  },
];

async function syncVideoScriptIdeas() {
  for (const idea of SCRIPT_IDEAS) {
    await pool.query(
      `INSERT INTO video_script_ideas
         (key, tool_slug, tool_name, hook, voiceover, cta_youtube, cta_reels_tiktok, caption, hashtags)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       ON CONFLICT (key) DO UPDATE SET
         tool_slug = EXCLUDED.tool_slug, tool_name = EXCLUDED.tool_name, hook = EXCLUDED.hook,
         voiceover = EXCLUDED.voiceover, cta_youtube = EXCLUDED.cta_youtube,
         cta_reels_tiktok = EXCLUDED.cta_reels_tiktok, caption = EXCLUDED.caption, hashtags = EXCLUDED.hashtags`,
      [idea.key, idea.toolSlug, idea.toolName, idea.hook, idea.voiceover,
        idea.ctaYoutube, idea.ctaReelsTiktok, idea.caption, idea.hashtags]
    );
  }
}

// Rotation: least-shown / longest-since-shown first, random tiebreak — so
// repeated use surfaces fresh ideas before old ones resurface.
async function getRandomIdeas(count) {
  const { rows } = await pool.query(
    `SELECT * FROM video_script_ideas
     ORDER BY times_shown ASC, last_shown_at ASC NULLS FIRST, RANDOM()
     LIMIT $1`,
    [count]
  );
  if (rows.length > 0) {
    await pool.query(
      `UPDATE video_script_ideas SET times_shown = times_shown + 1, last_shown_at = NOW() WHERE id = ANY($1::uuid[])`,
      [rows.map(r => r.id)]
    );
  }
  return rows;
}

module.exports = { SCRIPT_IDEAS, syncVideoScriptIdeas, getRandomIdeas };
